spring:
  profiles:
    active: prod
server:
  port: 8433
  ssl:
    key-store-type: PKCS12
    key-store-password: ericssondfc
    key-store: classpath:keystore.jks
    key-password: ericssondfc
    keyAlias: tomcat-localhost
logging:
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.onap.dcaegen2.collectors.datafile: TRACE
  file: opt/log/application.log
app:
  filepath: config/datafile_endpoints.json
